version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microjpeg-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.microjpeg.rule=Host(`hsksc4cs80s8kko8cg40cook.5.78.130.230.sslip.io`)"
      - "traefik.http.routers.microjpeg.entrypoints=http"
      - "traefik.http.services.microjpeg.loadbalancer.server.port=3000"

networks:
  coolify:
    external: true